# Generated by Django 4.1.6 on 2023-02-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=100)),
                ('refCode', models.CharField(max_length=100)),
                ('templateForm', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(null=True)),
                ('EndDate', models.DateTimeField(null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalGuardiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('bank', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('IBAN', models.CharField(max_length=100)),
                ('beneficjent', models.CharField(max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settelment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField(null=True)),
                ('EndDate', models.DateTimeField(null=True)),
                ('invoiceDate', models.DateTimeField(null=True)),
                ('paymentDate', models.DateTimeField(null=True)),
                ('documentPath', models.CharField(max_length=500)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('costApproval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Settlement_costApproval', to='settlement.costapproval')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('legalGuardiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_LegalGuardiant', to='settlement.legalguardiant')),
            ],
        ),
        migrations.AddField(
            model_name='costapproval',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CostApproval_insurance', to='settlement.insurance'),
        ),
        migrations.AddField(
            model_name='costapproval',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CostApproval_patient', to='settlement.patient'),
        ),
        migrations.AddField(
            model_name='costapproval',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CostApproval_payment', to='settlement.payment'),
        ),
    ]
