# Generated by Django 4.0.2 on 2023-01-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0003_legalcuardiant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalCuardiant',
            new_name='LegalGuardiant',
        ),
        migrations.AddField(
            model_name='patient',
            name='legalGuardiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_LegalGuardiant', to='settlement.legalguardiant'),
        ),
    ]
