# Generated by Django 4.1.6 on 2023-02-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0012_rename_type_insurance_insurance_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethode',
            old_name='type',
            new_name='pm_type',
        ),
    ]
