# Generated by Django 4.1.6 on 2023-02-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0013_rename_type_paymentmethode_pm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostApprovalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('templateForm', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='costapproval',
            name='templateForm',
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='ca_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CostApproval_CostApprovalType', to='settlement.costapprovaltype'),
        ),
    ]
