# Generated by Django 4.1.6 on 2023-02-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0014_costapprovaltype_remove_costapproval_templateform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settelment',
            new_name='Settlement',
        ),
    ]
