apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aequitas-app
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Custom
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cloudsql-instances: PROJECT_ID:us-central1:aequitas-db
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: aequitas-cloud-run@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/aequitas-app:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: DB_ENGINE
          value: django.db.backends.postgresql
        - name: DB_HOST
          value: /cloudsql/PROJECT_ID:us-central1:aequitas-db
        - name: DB_NAME
          value: aequitas
        - name: DB_USER
          value: aequitas_user
        - name: DB_PORT
          value: "5432"
        - name: DEBUG
          value: "0"
        - name: ENV
          value: PROD
        - name: USE_GUNICORN
          value: "1"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: django-secret-key
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 300
          timeoutSeconds: 30
          periodSeconds: 60
          failureThreshold: 3