# Generated by Django 4.1.6 on 2023-02-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_alter_costapproval_paymentmethode'),
    ]

    operations = [
    ]
