# Generated by Django 4.1.6 on 2023-02-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_auto_20230217_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settelment',
            name='EndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='settelment',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
