# Generated by Django 4.1.6 on 2023-02-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_alter_settelment_enddate_alter_settelment_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settelment',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settelment',
            name='invoiceDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settelment',
            name='paymentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settelment',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
