# Generated by Django 4.1.6 on 2023-02-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentMethode',
        ),
        migrations.RemoveField(
            model_name='costapproval',
            name='payment',
        ),
        migrations.AddField(
            model_name='costapproval',
            name='paymentMethode',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='CostApproval_paymentMethode', to='settlement.paymentmethode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='EndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
