# Generated by Django 4.1.6 on 2023-02-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0007_alter_settelment_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costapproval',
            old_name='type',
            new_name='ca_type',
        ),
    ]
