# Generated by Django 4.1.6 on 2023-02-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0009_address_remove_legalguardiant_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Address', to='settlement.address'),
        ),
    ]
