# Generated by Django 4.2.7 on 2023-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0015_rename_settelment_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='social_insurance_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
