# Generated by Django 5.2.6 on 2025-09-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0018_refactor_model_names_and_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'zip_code'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='costapproval',
            options={'ordering': ['-created'], 'verbose_name': 'Cost Approval', 'verbose_name_plural': 'Cost Approvals'},
        ),
        migrations.AlterModelOptions(
            name='costapprovaltype',
            options={'ordering': ['name'], 'verbose_name': 'Cost Approval Type', 'verbose_name_plural': 'Cost Approval Types'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'ordering': ['name'], 'verbose_name': 'Insurance', 'verbose_name_plural': 'Insurances'},
        ),
        migrations.AlterModelOptions(
            name='legalguardian',
            options={'ordering': ['display_name'], 'verbose_name': 'Legal Guardian', 'verbose_name_plural': 'Legal Guardians'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['display_name'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'ordering': ['-created'], 'verbose_name': 'Settlement', 'verbose_name_plural': 'Settlements'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='ca_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_approval_type', to='settlement.costapprovaltype'),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_approval_insurance', to='settlement.insurance'),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_approval_patient', to='settlement.patient'),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_approval_payment_method', to='settlement.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='ref_code',
            field=models.CharField(max_length=100, verbose_name='Reference Code'),
        ),
        migrations.AlterField(
            model_name='costapproval',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costapprovaltype',
            name='template_form',
            field=models.CharField(max_length=100, verbose_name='Template Form'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_address', to='settlement.address'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_type',
            field=models.CharField(max_length=250, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='legalguardian',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_guardian_address', to='settlement.address'),
        ),
        migrations.AlterField(
            model_name='legalguardian',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='legalguardian',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_address', to='settlement.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='legal_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_legal_guardian', to='settlement.legalguardian'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='cost_approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_cost_approval', to='settlement.costapproval'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='document_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='received_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='requested_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
