name: Deploy to Prod
on:
  pull_request:
    branches: [ "prod" ]

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: executing remote ssh commands using ssh key (git pull)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd prod/aequitas && git pull 

      - name: executing remote ssh commands using ssh key (build docker)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}        
          script: cd prod/aequitas && docker compose -p aequitas -f docker-compose-deploy.yml build

          
      - name: executing remote ssh commands using ssh key (deploy docker)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}        
          script: cd prod/aequitas && docker compose -p aequitas -f docker-compose-deploy.yml up -d
   
