name: Deploy to Test Server
on:
  pull_request:
    # Deploy to test only whoami new key
    branches:
      - 'test'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami